version: "3.3"
services:
  backend:
    build:
      context: ./backend
    image: openredact/backend:${TAG:-latest}
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    image: openredact/frontend:${TAG:-latest}
    ports:
      - "80:80"
