version: "3.3"
services:
  backend:
    build:
      context: ./backend
    image: openredact-backend
    ports:
      - "8000:8000"
    volumes:
      - "./backend/app:/app"
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: openredact-frontend-dev
    command: npm run start
    ports:
      - "80:80"
    volumes:
      - "./frontend:/app"
