version: "3.3"
services:
  backend:
    build:
       context: ./backend
       args:
        ssh_prv_key: $SSH_PRV_KEY
        ssh_pub_key: $SSH_PUB_KEY
    image: openredact-backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    image: openredact-frontend
    ports:
      - "80:80"
