name: Frontend Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  docker-build:
    runs-on: ubuntu-latest
    needs:
      - test
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v1
      - name: Build docker image
        run: |
          docker build  --cache-from openredact/frontend-dev:latest -t openredact/frontend-dev:${GITHUB_SHA} -f Dockerfile.dev .
          docker build  --cache-from openredact/frontend:latest -t openredact/frontend:${GITHUB_SHA} .
      - name: Push docker image (hash)
        run: |
          docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
          docker push openredact/frontend:${GITHUB_SHA}
          docker push openredact/frontend-dev:${GITHUB_SHA}
  docker-test-and-tag:
    runs-on: ubuntu-latest
    needs:
      - test
      - docker-build
    steps:
      - uses: actions/checkout@v1
      - name: Set up
        run: |
          sudo sysctl -w vm.max_map_count=262144
          docker --version
          docker-compose --version
      - name: Run tests in docker
        run: |
          TAG=${GITHUB_SHA} docker-compose -f docker-compose.dev.yml pull frontend-dev
          TAG=${GITHUB_SHA} docker-compose -f docker-compose.dev.yml run frontend-dev npm test  -- --watchAll=false
      - name: Push docker images for tags
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          export TAG=${GITHUB_REF/refs\/tags\//}
          docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
          docker tag openredact/frontend-dev:${GITHUB_SHA} openredact/frontend-dev:latest
          docker tag openredact/frontend:${GITHUB_SHA} openredact/frontend:latest
          docker push openredact/frontend-dev:latest
          docker push openredact/frontend:latest
